version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 15
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: daily
    groups:
      dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 15
