name: Qlue Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v7
        name: Checkout

      - uses: actions/setup-java@v6.0.1
        name: Set up JDK
        with:
          distribution: temurin
          java-version: |
            21
            25
            latest

      - name: Build with Maven
        run: mvn -B -ntp formatter:validate verify --file pom.xml "-Djava21.home=${{env.JAVA_HOME_21_X64}}${{env.JAVA_HOME_21_ARM64}}" "-Djava25.home=${{env.JAVA_HOME_25_X64}}${{env.JAVA_HOME_25_ARM64}}"
